In [87]:
import pandas as pd

In [88]:
df=pd.read_csv("Social_Network_Ads.csv")

In [99]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [100]:
# Age and EstimatedSalary are numerical values hence they are choosen as Independent Variables
# Purchased is a Dependent Variable


In [101]:
import numpy as np

In [102]:
X=df.loc[:,['Age','EstimatedSalary']].values
Y=df['Purchased'].values

In [103]:
from sklearn.model_selection import train_test_split

In [104]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.6,random_state=42)

In [105]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [106]:
from sklearn.linear_model import LogisticRegression

In [107]:
model=LogisticRegression()


In [108]:
model.fit(X_train,Y_train)

LogisticRegression()

In [109]:
y_prediction=model.predict(X_test)

In [110]:
y_prediction

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1],
      dtype=int64)

In [113]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((Y_test,y_prediction)).T
#actual value on the left side and predicted value on the right hand side
y_compare[:5,:]

array([[0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0]], dtype=int64)

In [114]:
# Confusion Matrix
# TN(actual & predicted F)     FP(predicted Y but actual F)
# FN(predicted N actual T)     TP(actual & predicted T)

In [115]:
from sklearn.metrics import confusion_matrix

In [116]:
confusion_m=confusion_matrix(Y_test,y_prediction)

In [117]:
confusion_m

array([[144,   5],
       [ 34,  57]], dtype=int64)

In [123]:
TN=confusion_m[0,0]
FP=confusion_m[0,1]
FN=confusion_m[1,0]
TP=confusion_m[1,1]
print('TN :',TN)
print('FP :',FP)
print('FN :',FN)
print('TP :',TP)

TN : 144
FP : 5
FN : 34
TP : 57


In [124]:
# Accuracy (all correct / all) = TP + TN / TP + TN + FP + FN

In [125]:
Accuracy=(TN+TP)/(TN+FP+FN+TP)

In [126]:
Accuracy

0.8375

In [127]:
# Precision (true positives / predicted positives) = TP / TP + FP

In [128]:
Precision=(TP)/(TP+FP)

In [129]:
Precision

0.9193548387096774

In [130]:
Error_Rate=(FP+FN)/(TN+FP+FN+TP)

In [131]:
Error_Rate

0.1625